# Shapekey names in official devkit are inconsitent between mannequin and body meshes, so....
profile_name = "Bibo"

[standard_materials]
"Bibo" = "/mt_c0201b0001_bibo.mtrl"
"Bibo Pubes" = "/mt_c0201b0001_bibopube.mtrl"

[[groups]]
group_name = "Top"
mode = "exclusive"
[groups.shapekeys]
"Small Chest" = "Small"
"Medium Chest" = "Medium"
"Large Chest" = "Large"
"XL Chest" = "X-Large"

[[groups]]
group_name = "Bottom"
mode = "exclusive"
[groups.shapekeys]
"Small" = "Small"
"Medium" = "Medium"
"Large" = "Large"
