profile_name = "Neolithe"

[standard_materials]
"Bibo" = "/mt_c0201b0001_bibo.mtrl"
"Bibo Pubes" = "/mt_c0201b0001_bibopube.mtrl"
"BPF" = "/mt_c0201b0001_betterpube.mtrl"
"Neolithe Piercings" = "/mt_c0201b0001_neolithe_piercings.mtrl"
"Top Undies" = "/mt_c0201e0000_top_neolithe_undies.mtrl"
"Bottom Undies" = "/mt_c0201e0000_dwn_neolithe_undies.mtrl"
"Nails" = "/mt_c0201b0001_neolithe_nails.mtrl"

[[groups]]
group_name = "Breast Size"
mode = "exclusive"
[groups.shapekeys]
"Flat" = "Flat"
"Default XS" = "XS"
"Default S (Default)" = "S"
"Default M" = "M"
"Default L" = "L"

[[groups]]
group_name = "Bottom"
mode = "exclusive"
[groups.shapekeys]
"S" = "S"
"M (Default)" = "M"
"L" = "L"

[[groups]]
group_name = "Body"
mode = "optional"
[groups.shapekeys]
"Neobelly" = "Neobelly"
"Buff" = "Buff"
"Shin Thicker" = "Thicker Shins"