profile_name = "YAB"
# Devkit uses a script for shapes, delete drivers manually

[profile_info]
summary = "YAB requires a small setup"
instructions = [
    "Remember to adjust body mesh names to '*name* X.Y' format instead of 'X.Y *name*'",
	"I recommend using newest YABKit and deactivating it in settings",
    "You can deactivate it by opening Devkit panel, changing to settings tab, ",
    "and pressing Deactivate Devkit"
]


[standard_materials]
"Bibo" = "/mt_c0201b0001_bibo.mtrl"
"Bibo Pubes" = "/mt_c0201b0001_bibopube.mtrl"
"BPF" = "/mt_c0201b0001_betterpube.mtrl"
# TODO: Add piercings material

[[groups]]
group_name = "Top"
mode = "exclusive"
[groups.shapekeys]
"LARGE" = "Large"
"MEDIUM" = "Medium"
"SMALL" = "Small"
"MASC" = "Masc"

[[groups]]
group_name = "Bottom"
mode = "exclusive"
[groups.shapekeys]
"Watermelon Crushers" = "Watermelon Crushers"
"Skull Crushers" = "Skull Crushers"
"Masc" = "Masc"

[[groups]]
group_name = "Body"
mode = "optional"
[groups.shapekeys]
"Rue" = "Rue"
"Buff" = "Buff"
"Small Butt" = "Small Butt"
"Soft Butt" = "Soft Butt"
[export_aliases]
"Rue" = "Rue"